# -*- coding: utf-8 -*-
"""ch3_exercises.py23.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/147weYnUG4fmOjcynAzbZIoJI4FqTf2lR

## ch3_exercises.ipynb

## Q1.
> 다음 코드의 결괏값은 무엇일까?

```
a = "Life is too short, you need python"
if "wife" in a: print("wife")
elif "python" in a and "you" not in a: print("python")
elif "shirt" not in a: print("shirt")
elif "need" in a: print("need")
else: print("none")

```
"""

# [Q1] Code  
if "wife" in a: print("wife") #wife에는 a가 안들어가 있기 때문에 출력되지 않는다.
elif "python" in a and "you" not in a: print("python") #you에는 a가 없지만, python에 a에 들어가 있지 않기 때문에 실행이 되지 않는다.
elif "shirt" not in a: print("shirt") #shirt란 단어가 안들어가 있기 때문에 출력된다.
elif "need" in a: print("need") #need란 단어가 있지만 이미 elif가 실행됐기 때문에 실행이 되지 않는다.
else: print("none") #만약 위 조건에서 맞는게 없다면 none이 출력된다.

"""## Q2.
> while문을 사용해 1부터 1000까지의 자연수 중 3의 배수의 합을 구해 보자.
"""

# [Q2] Code
a=0
all=0
while a < 1000:
  a=a+1
  if a%3==0:
    all=all+a
  else: continue
print(all)

"""## Q3.
> while문을 사용하여 다음과 같이 별(*)을 표시하는 프로그램을 작성해 보자.

```
*
**
***
****
*****

```
"""

# [Q3] Code1
a=0
while a<5:
  a+=1 
  print("*"*a)

"""## Q4.
> for문을 사용해 1부터 100까지의 숫자를 출력해 보자.
- 단순 for문 사용
- 리스트 내포 사용
"""

# [Q4] Code1 
a = [1, 2, 3]
a.extend([4, 5])
a

"""## Q5.
> A 학급에 총 10명의 학생이 있다. 이 학생들의 중간고사 점수는 다음과 같다.

- [70, 60, 55, 75, 95, 90, 80, 80, 85, 100]

- for문을 사용하여 A 학급의 평균 점수를 구해 보자.
"""

# [Q5] Code2
a=[70, 60, 55, 75, 95, 90, 80, 80, 85, 100]
sum=0
for i in range(0,10):
  sum+=a[i]
print(sum/10)

"""## Q6.
> 리스트 중에서 홀수에만 2를 곱하여 저장하는 다음 코드가 있다.
```
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
result = []
for n in numbers:
    if n % 2 == 1:
        result.append(n*2)
```

- 위 코드를 리스트 내포(list comprehension)를 사용하여 표현해 보자.
"""

# [Q6] Code
a = "Life is too short"
a.split()
b = "a:b:c:d"
b.split(':')

"""## Q7.
> ## [Challenge] 응용 코드 : 평균 성적을 구하시오.
```
subjects = ['파이썬', '영어', '수학', '물리']
scores = [91, 67, 88, 75]
```

- 평균 성적을 세가지 이상의 방법으로 구하시오.
"""

# [Q7] Code-1
a = ['파이썬', '영어', '수학', '물리']
b = [91, 67, 88, 75]
sum=0
for i in range(0,4):
  a[i]=b[i]
  sum+=a[i]
print("과목 개수:",len(a))
average=sum/(len(a))
print("평균: %.2f" %average)

# [Q7] Code-2
a = ['파이썬', '영어', '수학', '물리']
b = [91, 67, 88, 75]
sum=0
for i in range(0,4):
  sum+=b[i]
print(sum/4)

# [Q7] Code-3
a=[]
a.append(input("파이썬 점수:"))
a.append(input("영어 점수:"))
a.append(input("수학 점수:"))
a.append(input("물리 점수:"))
sum=int(a[0])+int(a[1])+int(a[2])+int(a[3])
average=sum/4
print ("평균: %.2f"%average)

"""## 코딩 연습 결과를 github에 올리기
> 완성된 ipython 노트북 파일을 각자의 github에 올리시오.

- github 계정 만들기 (계정이 없는 학생)
    1. github에 sign up (Google gmail 계정을 이용해서 만드시오.)
- github에 노트 올리기
    2. github에 각자의 id로 repo를 만드시오. (한번 만들면 계속 재사용)
    3. github repo에 연습결과 노트를 올리시오.
        - 제출노트: ch3_exercises_id.ipynb
"""

